package zm.gov.moh.common;

public class ModuleConfig {

    //Vitals
    public static final String CONCEPT_UUID_RESPIRATORY_RATE = "5242AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String CONCEPT_UUID_SYSTOLIC_BLOOD_PRESSURE = "5085AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String CONCEPT_UUID_DIASTOLIC_BLOOD_PRESSURE = "5086AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String CONCEPT_UUID_PULSE = "5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String CONCEPT_UUID_TEMPERATURE = "5088AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String CONCEPT_UUID_WEIGHT = "5089AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String CONCEPT_UUID_HEIGHT = "5090AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String CONCEPT_UUID_BLOOD_OXYGEN_SATURATION = "5092AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    //Encounter types
    public static final String ENCOUNTER_TYPE_UUID_VITALS = "67a71486-1a54-468f-ac3e-7091a9a79584";

    //Visit types
    public static final String VISIT_TYPE_UUID_FACILITY_VISIT = "7b0f5697-27e3-40c4-8bae-f4049abfb4ed";
}
