package zm.gov.moh.common.submodule.login.model;

public enum ViewState {
    NO_INTERNET, NO_CREDENTIALS, AUTHORIZED, UNAUTHORIZED, UNAUTHORIZED_LOCATION, USER_NOT_PROVIDER, MULTIPLE_LOCATION_SELECTION, TIMEOUT, UNREACHABLE_SERVER, PENDING
}